Update iphunter

diff --git a/iphunter b/iphunter
--- a/iphunter
+++ b/iphunter
@@ -1,7 +1,7 @@
 #!/bin/bash
 function Header() {
     clear
-echo -e "$(tput setaf 2)
+echo -e "\n\n$(tput setaf 2)
  ___         _   _             _            
 |_ _|_ __   | | | |_   _ _ __ | |_ ___ _ __ 
  | || '_ \  | |_| | | | | '_ \| __/ _ \ '__|
@@ -14,23 +14,29 @@ function ReqCheck() {
     #check nmap
     reqmet=""
     echo "Checking requirements:"
-if [[ `tshark -v 2>/dev/null` == *"Wireshark"* ]]
+if [[ `ip -V 2>/dev/null` == *"iproute2"* ]]
 then
-    echo -e "\n\033[1;32mPASS:\033[0m tshark (wireshark-cli)"
-    if [[ `nmap -V 2>/dev/null` == *"Nmap version"* ]]
+    echo -e "\n\033[1;32mPASS:\033[0m ip (iproute2)"
+    if [[ `tshark -v 2>/dev/null` == *"Wireshark"* ]]
     then
-        echo -e "\033[1;32mPASS:\033[0m nmap (nmap)\n"
+        echo -e "\033[1;32mPASS:\033[0m tshark (wireshark-cli)"
+        if [[ `nmap -V 2>/dev/null` == *"Nmap version"* ]]
+        then
+            echo -e "\033[1;32mPASS:\033[0m nmap (nmap)\n"
+        else
+            echo -e "\033[91mFAIL:\033[0m Please install nmap (package name: nmap) on LINUX or (brew install nmap) on a MAC\n" && exit 1
+        fi
     else
-        echo -e "\033[91mFAIL:\033[0m Please install nmap (package name: nmap) on LINUX or (brew install nmap) on a MAC\n" && exit 1
+        echo -e "\033[91mFAIL:\033[0m Please install tshark (wireshark-cli) on LINUX or (brew install wireshark) on a MAC\n" && exit 1
     fi
 else
-    echo -e "\n\033[91mFAIL:\033[0m Please install tshark (wireshark-cli) on LINUX or (brew install wireshark) on a MAC\n" && exit 1
+    echo -e "\033[91mFAIL:\033[0m Please install ip (package name: iproute2) on LINUX or (brew install iproute2mac) on a MAC\n" && exit 1
 fi
 }
 
 function Scan () {
     sudo tshark -i ${1} -w /var/scanOutput.pcap > /dev/null 2>&1 &
-    PID=$!
+    pid=`pgrep tshark`
     for (( i=1; i<=$scantime; i++ ))
     do
     calc=$((i*100/$scantime))
@@ -38,7 +44,8 @@ function Scan () {
    sleep 1
 done
 echo -ne 'Done scanning  \n'
-killall tshark -9 2> /dev/null
+
+sudo kill -9 "$pid" > /dev/null 2>&1
 }
 
 ipnetcut=""
@@ -57,7 +64,7 @@ function KickThemOut () {
     # $1 is the gateway <---> $2 is the wireless interface
     ipbeg=`echo "$1" |cut -d '.' -f 1,2`
     ipscan=`sudo nmap -iflist | grep "$2" | awk -v ip="$ipbeg" '$1 ~ ip { print $1}' | awk -F "." '$4 ~ /^0/ {print $0}'` 
-        ips=`sudo nmap -T5 -sP "$ipscan" -e "$2" | grep "for" | awk '$5 !~ /\.1$/ && $5 ~ /^[0-9]/ {print $5}'`
+    ips=`sudo nmap -T5 -sP $ipscan -e "$2" | grep "for" | awk '$5 !~ /\.1$/ && $5 ~ /^[0-9]/ {print $5}'`    
     fakemac=`arp -an | grep "$1)" | awk '{print $4}'`
     while IFS= read -r ip
     do
@@ -80,20 +87,19 @@ function Run () {
     int=$1
     if [ -z $scantime ]
     then
-    echo -en "Enter scan timout (default 30s): "
+    echo -en "Enter scan timout (default 10s): "
     read scantime
-    [ -z $scantime ] && scantime=30
+    [ -z $scantime ] && scantime=1
     Scan $1
     else
     let "scantime=$scantime*2"
     echo -e "Scan timout is now doubled to ${scantime}s"
     Scan $1
     fi
-    gateway=`netstat -nr | grep default | awk '{print $2}'`
+    gateway=`ip route | grep "default" | awk '{print $3}'`
     broadcast=`ifconfig $1 | grep broadcast | awk '{print $6}'`
     ips=`sudo tshark -o 'gui.column.format:"Dest","%d","Protocol","%p","Info","%i"' -r /var/scanOutput.pcap 2> /dev/null | grep ARP |grep Broadcast |grep Tell | awk '{print substr($5, 1, length($5)-1),$7}' | awk -v gt="$gateway" '$2 !~ gt {print $0}' | sort -k 2 | uniq`
     ipbeg=`echo "$gateway" |cut -d '.' -f 1,2,3`
-    ips2=`tshark -r /var/scanOutput.pcap | awk -v ipbeg="$ipbeg" '$3 ~ ipbeg {print $3}' | sort -u | grep -v "$gateway"`
     IFS=\n
     NetCut $ips $gateway; [[ $ipnetcut == "" ]] && KickThemOut "$gateway" "$int"
     unset IFS
